### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Also merged in AnacondaRecipes changes

**Comment by mariusvniekerk** [comment]
cc @conda-forge/core I've updated this one to get built again.  Seems we did not have run_exports on here so we may need a migration

**Comment by scopatz** [comment]
LGTM - need @mingwandroid to approve

**Comment by CJ-Wright** [comment]
This isn't currently globally pinned so the bot isn't really set up to do a migration at the moment.

**Review by mingwandroid — APPROVED** [review]

**Pull request merged**
